# Workshop Hands-on - Deploy OCP 4.x IPI on Google Cloud Platform


=== Start OCP 4 install

As soon as, all of your prerequisites done and you have the install-config.yaml it's now time to finnaly install your cluster.
----
./openshift-install create cluster --dir=install --log-level=debug
----
Wait until Openshift Cluster Api up until get the credentials to login to the cluster.

#### Running oc commands

Configure kubeconfig in your profile to be able to run oc commands:

----
mkdir ~/.kube/
cp auth/kubeconfig ~/.kube/config
----

#### Final installation steps

After the cluster finishes to start the installation you must check if all things are running well, so:

1. Check Nodes  
    
Looking that all nodes must be "Ready" state.
[source]
----
oc get nodes -o wide
----


2. Check Operators

Check all columns, operators must be "TRUE" on "AVAILABLE" column:
[source]
----
oc get co
----

3. Check Ingress
Check that ingresscontroller created at least a pair of ingresses at different nodes
[source]
----
oc get ingress -o wide -n openshift-ingress
----

4. Check Authentication and Console

On OCP 4.x authentication depends on ingresscontrollers properly working, and console depends on ingresses to dispose the pods along wildcards route and also to authentication to authenticate on console and OCP Web Interface.

Try to reach the URL: https://console-openshift-console.apps.<clusterId>.<domain>
Login with kubeadmin credentials which can be find on your installation directory/auth/kubeadmin-password


Now you are ready do proceed with post installation deployment.
