# Workshop Hands-on - Deploy OCP 4.x on Google Cloud

### Post deployment configuration

After cluster is up and running it is important to add further features to best organize and easy maintenance of cluster.

In the next steps, you will accomplish the following tasks:

1. link:infra-worker.adoc[Create infra nodes and setup taints and tolerations strategy].
2. link:ingresscontroller.adoc[Adjust ingresscontroller default to run only on infra nodes]. 
3. link:monitoring.adoc[Provisioning monitoring stack to run only on infra nodes].
4. link:registry.adoc[Provisioning Registry to run only on infra nodes and ephemeral mode].
5. link:authentication.adoc[Configuring httpd authentication and export oauth CRD in order to add new identity providers]
6. link:logging.adoc[Create a Cluster Logging stack fully automated].


#### Set registry storage storage to use an ephemeral volume:

----
oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"emptyDir":{}}}}'
----

[NOTE]
====
In production environments set the registry storage with some supported persistent storage such as OCS or NFS.
====

#### Set ingress configuration

----
oc get -n openshift-ingress-operator ingresscontrollers/default -o jsonpath='{$.spec.replicas}'
2
oc patch -n openshift-ingress-operator ingresscontroller/default --patch '{"spec":{"replicas": <NUM_OF_ROUTER_REPLICAS>}}' --type=merge
ingresscontroller.operator.openshift.io/default patched
----

#### Config authentication with httpd

----
sudo yum install httpd-tools
htpasswd -c -B -b users.htpasswd admin 'passwd'
oc create secret generic htpass-secret --from-file=htpasswd=users.htpasswd -n openshift-config

cat <<EOF > htpasswd-conf.yml
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: my_htpasswd_provider 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret 
EOF

oc apply -f htpasswd-conf.yml
oc adm policy add-cluster-role-to-user cluster-admin admin

oc delete secrets kubeadmin -n kube-system
----

